#pip install mkdocs
#pip install mkdocs-glightbox
#pip install pymdown-extensions
#pip install mkdocs-pymdownx-material-extras
#mkdocs build ; mkdocs serve

#==============================================================
# NEW VERSION CHECKLIST
#==============================================================
# update version in madflight.h
# update version in library.properties
# create new madflight release
# Open PlatformIO Core CLI: pio pkg publish C:\path\to\Arduino\libraries\madflight
# make new github release of existing madflight-docs version
# update madflight-docs version in this file
#==============================================================

site_name: madflight v2.1.3

nav:
  - Intro: index.md
  - Getting Started:
      - Getting Started: Getting-Started.md
      - ESP32-S3 / ESP32: Board-ESP32.md
      - RP2350 / RP2040: Board-RP2040.md
      - STM32: Board-STM32.md
      - madflight FC2 - ESP32-S3: Board-ESP-FC2.md
      - madflight FC3 - RP2350B: Board-FC3.md
  - Examples:
      - Quadcopter: Example-Quadcopter.md
      - Quadcopter Advanced: Example-Quadcopter-Advanced.md
      - Plane: Example-Plane.md
  - Reference:
      - Developer Guide: Developer-Guide.md
      - MAVLink: MAVLink.md
      - Black Box Logging: Black-Box.md
      - Controller Boards: Controller-Boards.md
      - Sensor Boards: Sensor-Boards.md
      - AHRS: AHRS.md
      - Lua: Lua.md
      - GPS Configuration: GPS-Configuration.md
      - GPS Messages: GPS-Messages.md
      - Digital Low-pass Filter: Digital-Low-pass-Filter.md
      - madflight FC1 - RP2350B: Board-FC1.md

site_url: https://madflight.com/
site_description: madflight DIY Flight Controller
site_author: qqqlab

copyright: Copyright &copy; 2025 qqqlab

use_directory_urls: true

theme: readthedocs

markdown_extensions:
  - tables

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: 

  # Python Markdown Extensions
#  - pymdownx.arithmatex:
#      generic: true
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.keys
  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - pymdownx.tilde

plugins:
  - search:
      min_search_length: 3
      indexing: 'full'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true

use_directory_urls: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/mathjaxhelper.js

extra_css:
  - css/extra.css
